import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/container/layout/Header';
import Footer from '@/container/layout/Footer';
import Head from 'next/head';
import Script from 'next/script';
import localFont from 'next/font/local';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const partialSans = localFont({
  src: '../../public/fonts/PartialSansKR-Regular.otf',
  variable: '--font-partialSans',
  display: 'swap',
});

const paperlogy = localFont({
  variable: '--font-paperlogy',
  display: 'swap',
  src: [
    {
      path: '../../public/fonts/Paperlogy-1Thin.ttf',
      weight: '100',
      style: 'thin',
    },
    {
      path: '../../public/fonts/Paperlogy-2ExtraLight.ttf',
      weight: '200',
      style: 'extralight',
    },
    {
      path: '../../public/fonts/Paperlogy-3Light.ttf',
      weight: '300',
      style: 'light',
    },
    {
      path: '../../public/fonts/Paperlogy-4Regular.ttf',
      weight: '400',
      style: 'regular',
    },
    {
      path: '../../public/fonts/Paperlogy-5Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../../public/fonts/Paperlogy-6SemiBold.ttf',
      weight: '600',
      style: 'semi-bold',
    },
    {
      path: '../../public/fonts/Paperlogy-7Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/fonts/Paperlogy-8ExtraBold.ttf',
      weight: '800',
      style: 'extra-bold',
    },
    {
      path: '../../public/fonts/Paperlogy-9Black.ttf',
      weight: '900',
      style: 'black',
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={` ${partialSans.variable} ${paperlogy.variable} ${inter.className}      flex flex-col min-h-screen`}
      >
        {/* <Header /> */}
        <Script
          async
          src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7991043744509425'
          crossOrigin='anonymous'
        ></Script>
        <main className=''>{children}</main>
        <div id='modal-root'></div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
